#!/bin/sh
set -e

case "$1" in
    remove|purge|disappear)
        # Remove this application's shortcuts from every existing Wine prefix.
        /usr/share/cusdeb/cdex/cdex-shortcut-helper remove \
            "-" \
            "Games\\Spider Solitaire"
        ;;
    upgrade|failed-upgrade|abort-install|abort-upgrade)
        ;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0
