#!/bin/sh
set -e

case "$1" in
    remove|purge|disappear)
        if [ -x /usr/share/cusdeb/cdex/cdex-shortcut-helper ]; then
            /usr/share/cusdeb/cdex/cdex-shortcut-helper remove \
                "-" \
                "Games\\Minesweeper"
        fi
        ;;
    upgrade|failed-upgrade|abort-install|abort-upgrade)
        ;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0
