#!/bin/sh
set -e

if [ "$1" = "remove" ] || [ "$1" = "deconfigure" ]; then
    if [ -x /usr/sbin/update-binfmts ]; then
        /usr/sbin/update-binfmts --package wine --remove wine /usr/bin/wine || true
    fi
fi

#DEBHELPER#

exit 0
