backend: apt

operations:
  - remove:
      - "^live-*"
      - calamares-settings-debian
      - calamares
      - user-setup
      - qml6-module-qtqml
      - qml6-module-qtqml-models
      - qml6-module-qtqml-workerscript
      - qml6-module-qtquick
      - qml6-module-qtquick-window
