# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
---
efi:
    mountPoint:         "/boot/efi"
    recommendedSize:    300MiB
    minimumSize:        32MiB
    label:              "EFI"

userSwapChoices:
    - none
    - small
    - suspend
    - file

initialPartitioningChoice: none
initialSwapChoice: none

defaultFileSystemType:  "ext4"

essentialMounts: [ "live-*", "control", "ventoy" ]

luksGeneration: luks2

lvm:
    enable: false
